### ISSUE TITLE
Change X logo to blue bird logo

### ISSUE THREAD

**Issue by Armstrong2035** [codiejay/retrotwitter#1]
The logo on the top left corner of Twitter is X. Let's return the original one!

**Comment by codiejay** [comment]
This has been updated. But need to wait for Google to approve it before the extension gets updated. Great catch! Thanks @Armstrong2035  

Here's the snippet of code that fixes that: 

```
const siteIcon = document.querySelector('link[rel="shortcut icon"]');
siteIcon.href = 'https://abs.twimg.com/responsive-web/client-web/icon-svg.168b89da.svg';
```

**Comment by Armstrong2035** [comment]
Ayy thank you so much bossman!
