### ISSUE TITLE
Remove "Verified Orgs" from the Navigation Bar

### ISSUE THREAD

**Issue by Armstrong2035** [codiejay/retrotwitter#2]

**Comment by codiejay** [comment]
Why will we want to? It is a perk for users who bought Twitter Blue.

**Comment by Armstrong2035** [comment]
> Why will we want to? It is a perk for users who bought Twitter Blue.

Fair enough. I thought we were going for the full interface

**Comment by Armstrong2035** [comment]
> Why will we want to? It is a perk for users who bought Twitter Blue.

Fair enough. I thought we were going for the full interface

**Comment by codiejay** [comment]
So you mean to suggest a total revamp to restore how twitter looked like before Elon took over?

**Comment by Armstrong2035** [comment]
> So you mean to suggest a total revamp to restore how twitter looked like before Elon took over? 

That's what I was thinking 🤔
